# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('createDate', models.DateField(auto_now_add=True, null=True)),
                ('numberOfTopics', models.IntegerField()),
                ('notes', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plik_zip', models.FileField(upload_to='documents/')),
                ('Plik_konfiguracyjny', models.FileField(upload_to='documents/')),
                ('Ilość_tematów', models.SmallIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
