# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Autor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='Nazwa_korpusu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='Opis_korpusu',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
