# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 12:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Corpuses',
        ),
        migrations.AddField(
            model_name='document',
            name='Autor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='Nazwa_korpusu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='Opis_korpusu',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='Plik_konfiguracyjny',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions='xlsx, xls', code='zły rodzaj pliku', message='Plik musi mieć rozszerzenie .xls lub .xlsx')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='Plik_zip',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions='zip', code='zły rodzaj pliku', message='Plik musi mieć rozszerzenie .zip')]),
        ),
    ]
