# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='xml_file',
            new_name='excel_file',
        ),
    ]
