# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170503_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='excel_file',
            new_name='Plik_konfiguracyjny',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='zip_file',
            new_name='Plik_zip',
        ),
        migrations.RemoveField(
            model_name='document',
            name='your_email',
        ),
        migrations.AddField(
            model_name='document',
            name='Email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='Ilość_tematów',
            field=models.SmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
