# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170514_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Plik_konfiguracyjny',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions='xlsx, xls', code='zły rodzaj pliku', message='Plik musi mieć rozszerzenie .xls lub .xlsx')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='Plik_zip',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions='zip', code='zły rodzaj pliku', message='Plik musi mieć rozszerzenie .zip')]),
        ),
    ]
