# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 14:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_delete_dane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='Ilość_tematów',
            new_name='Ilosc_tematow',
        ),
        migrations.AlterField(
            model_name='document',
            name='Plik_konfiguracyjny',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions='xlsx, xls', code='zly rodzaj pliku', message='Plik musi miec rozszerzenie .xls lub .xlsx')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='Plik_zip',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions='zip', code='zly rodzaj pliku', message='Plik musi miec rozszerzenie .zip')]),
        ),
    ]
